# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Task Manager Java with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: mvn -B test site
      - name: Upload test reports (Surefire + Site)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/**
            target/site/**

  build:
    runs-on: ubuntu-latest
    # roda em paralelo com "tests"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven (skip tests)
        run: mvn -B -DskipTests package
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-manager-jar
          path: target/*.jar

  notify:
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
      - uses: actions/checkout@v4
      - name: Send email notification
        env:
          NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          STATUS_TESTS: ${{ needs.tests.result }}
          STATUS_BUILD: ${{ needs.build.result }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: python3 scripts/send_mail.py


